create table if not exists article_translation_sessions (
  id bigint generated by default as identity primary key,
  article_id bigint not null references articles(id) on delete cascade,
  source_html_hash text not null,
  status text not null,
  total_segments int not null default 0,
  translated_segments int not null default 0,
  failed_segments int not null default 0,
  started_at timestamptz not null default now(),
  finished_at timestamptz null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint article_translation_sessions_status_check check (status in ('running', 'succeeded', 'partial_failed', 'failed'))
);

create unique index if not exists article_translation_sessions_article_id_unique
  on article_translation_sessions (article_id);
create index if not exists article_translation_sessions_status_updated_at_idx
  on article_translation_sessions (status, updated_at desc);

create table if not exists article_translation_segments (
  id bigint generated by default as identity primary key,
  session_id bigint not null references article_translation_sessions(id) on delete cascade,
  segment_index int not null,
  source_text text not null,
  translated_text text null,
  status text not null default 'pending',
  error_code text null,
  error_message text null,
  started_at timestamptz null,
  finished_at timestamptz null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint article_translation_segments_status_check check (status in ('pending', 'running', 'succeeded', 'failed'))
);

create unique index if not exists article_translation_segments_session_id_segment_index_unique
  on article_translation_segments (session_id, segment_index);
create index if not exists article_translation_segments_session_id_status_idx
  on article_translation_segments (session_id, status);

create table if not exists article_translation_events (
  event_id bigserial primary key,
  session_id bigint not null references article_translation_sessions(id) on delete cascade,
  segment_index int null,
  event_type text not null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists article_translation_events_session_event_id_idx
  on article_translation_events (session_id, event_id);
