create table if not exists system_logs (
  id bigint generated by default as identity primary key,
  level text not null check (level in ('error', 'warning', 'info')),
  category text not null,
  message text not null,
  details text null,
  source text not null,
  context_json jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_system_logs_created_at_desc
  on system_logs (created_at desc, id desc);

create index if not exists idx_system_logs_level_created_at_desc
  on system_logs (level, created_at desc, id desc);
