create table if not exists article_media_attachments (
  id bigint generated by default as identity primary key,
  article_id bigint not null references articles(id) on delete cascade,
  url text not null,
  mime_type text not null,
  size_bytes bigint null,
  duration_seconds int null,
  position int not null default 0,
  created_at timestamptz not null default now()
);

create index if not exists article_media_attachments_article_id_idx
  on article_media_attachments (article_id);

create unique index if not exists article_media_attachments_article_url_unique
  on article_media_attachments (article_id, url);
