alter table feeds
  add column if not exists provider text not null default 'local_rss';

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'feeds_provider_check'
  ) then
    alter table feeds
      add constraint feeds_provider_check
      check (provider in ('local_rss', 'fever'));
  end if;
end $$;

create table if not exists fever_accounts (
  id bigint generated by default as identity primary key,
  base_url text not null,
  username text not null,
  api_key text not null,
  enabled boolean not null default true,
  last_sync_at timestamptz null,
  last_error text null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists fever_feed_mappings (
  fever_account_id bigint not null references fever_accounts(id) on delete cascade,
  fever_feed_id text not null,
  local_feed_id bigint not null references feeds(id) on delete cascade,
  remote_group_name text null,
  remote_title text not null,
  remote_url text not null,
  remote_favicon_url text null,
  is_active boolean not null default true,
  last_seen_at timestamptz not null default now(),
  primary key (fever_account_id, fever_feed_id)
);

create table if not exists fever_item_mappings (
  fever_account_id bigint not null references fever_accounts(id) on delete cascade,
  fever_item_id text not null,
  fever_feed_id text not null,
  local_feed_id bigint not null references feeds(id) on delete cascade,
  local_article_id bigint not null references articles(id) on delete cascade,
  remote_is_read boolean not null default false,
  remote_is_saved boolean not null default false,
  remote_created_at timestamptz null,
  is_active boolean not null default true,
  last_seen_at timestamptz not null default now(),
  primary key (fever_account_id, fever_item_id)
);

create table if not exists fever_sync_states (
  fever_account_id bigint primary key references fever_accounts(id) on delete cascade,
  last_incremental_item_id text null,
  last_incremental_synced_at timestamptz null,
  last_full_sync_at timestamptz null,
  last_error text null,
  updated_at timestamptz not null default now()
);
