create table if not exists users (
  id bigint generated by default as identity primary key,
  username text not null,
  password_hash text not null default '',
  role text not null default 'member',
  status text not null default 'active',
  session_version int not null default 1,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint users_role_check check (role in ('admin', 'member')),
  constraint users_status_check check (status in ('active', 'disabled'))
);

create unique index if not exists users_username_unique
  on users (lower(username));

insert into users (username, password_hash, role, status)
values ('admin',
  coalesce((select auth_password_hash from app_settings where id = 1), ''),
  'admin',
  'active'
)
on conflict do nothing;

create table if not exists user_settings (
  user_id bigint primary key references users(id) on delete cascade,
  ui_settings jsonb not null default '{}'::jsonb,
  ai_api_key text not null default '',
  translation_api_key text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

insert into user_settings (user_id, ui_settings, ai_api_key, translation_api_key)
select
  users.id,
  coalesce((select ui_settings from app_settings where id = 1), '{}'::jsonb),
  coalesce((select ai_api_key from app_settings where id = 1), ''),
  coalesce((select translation_api_key from app_settings where id = 1), '')
from users
where username = 'admin'
on conflict (user_id) do nothing;

-- 先添加 nullable 列并按父级资源回填，最后统一收紧 not null。
alter table categories add column if not exists user_id bigint;
alter table feeds add column if not exists user_id bigint;
alter table articles add column if not exists user_id bigint;
alter table fever_accounts add column if not exists user_id bigint;
alter table fever_feed_mappings add column if not exists user_id bigint;
alter table fever_item_mappings add column if not exists user_id bigint;
alter table fever_sync_states add column if not exists user_id bigint;
alter table ai_digest_configs add column if not exists user_id bigint;
alter table ai_digest_runs add column if not exists user_id bigint;
alter table feed_refresh_runs add column if not exists user_id bigint;
alter table feed_refresh_run_items add column if not exists user_id bigint;
alter table article_tasks add column if not exists user_id bigint;
alter table article_translation_sessions add column if not exists user_id bigint;
alter table article_translation_segments add column if not exists user_id bigint;
alter table article_translation_events add column if not exists user_id bigint;
alter table article_ai_summary_sessions add column if not exists user_id bigint;
alter table article_ai_summary_events add column if not exists user_id bigint;
alter table article_media_attachments add column if not exists user_id bigint;
alter table feed_favicons add column if not exists user_id bigint;
alter table ai_digest_run_sources add column if not exists user_id bigint;
alter table system_logs add column if not exists user_id bigint;

update categories set user_id = (select id from users where username = 'admin') where user_id is null;
update feeds set user_id = (select id from users where username = 'admin') where user_id is null;
update articles set user_id = feeds.user_id
from feeds
where articles.feed_id = feeds.id
  and articles.user_id is null;
update fever_accounts set user_id = (select id from users where username = 'admin') where user_id is null;
update fever_feed_mappings set user_id = fever_accounts.user_id
from fever_accounts
where fever_feed_mappings.fever_account_id = fever_accounts.id
  and fever_feed_mappings.user_id is null;
update fever_item_mappings set user_id = fever_accounts.user_id
from fever_accounts
where fever_item_mappings.fever_account_id = fever_accounts.id
  and fever_item_mappings.user_id is null;
update fever_sync_states set user_id = fever_accounts.user_id
from fever_accounts
where fever_sync_states.fever_account_id = fever_accounts.id
  and fever_sync_states.user_id is null;
update ai_digest_configs set user_id = feeds.user_id
from feeds
where ai_digest_configs.feed_id = feeds.id
  and ai_digest_configs.user_id is null;
update ai_digest_runs set user_id = feeds.user_id
from feeds
where ai_digest_runs.feed_id = feeds.id
  and ai_digest_runs.user_id is null;
update feed_refresh_runs set user_id = coalesce(
  (select feeds.user_id from feeds where feeds.id = feed_refresh_runs.feed_id),
  (select id from users where username = 'admin')
)
where user_id is null;
update feed_refresh_run_items set user_id = feed_refresh_runs.user_id
from feed_refresh_runs
where feed_refresh_run_items.run_id = feed_refresh_runs.id
  and feed_refresh_run_items.user_id is null;
update article_tasks set user_id = articles.user_id
from articles
where article_tasks.article_id = articles.id
  and article_tasks.user_id is null;
update article_translation_sessions set user_id = articles.user_id
from articles
where article_translation_sessions.article_id = articles.id
  and article_translation_sessions.user_id is null;
update article_translation_segments set user_id = article_translation_sessions.user_id
from article_translation_sessions
where article_translation_segments.session_id = article_translation_sessions.id
  and article_translation_segments.user_id is null;
update article_translation_events set user_id = article_translation_sessions.user_id
from article_translation_sessions
where article_translation_events.session_id = article_translation_sessions.id
  and article_translation_events.user_id is null;
update article_ai_summary_sessions set user_id = articles.user_id
from articles
where article_ai_summary_sessions.article_id = articles.id
  and article_ai_summary_sessions.user_id is null;
update article_ai_summary_events set user_id = article_ai_summary_sessions.user_id
from article_ai_summary_sessions
where article_ai_summary_events.session_id = article_ai_summary_sessions.id
  and article_ai_summary_events.user_id is null;
update article_media_attachments set user_id = articles.user_id
from articles
where article_media_attachments.article_id = articles.id
  and article_media_attachments.user_id is null;
update feed_favicons set user_id = feeds.user_id
from feeds
where feed_favicons.feed_id = feeds.id
  and feed_favicons.user_id is null;
update ai_digest_run_sources set user_id = ai_digest_runs.user_id
from ai_digest_runs
where ai_digest_run_sources.run_id = ai_digest_runs.id
  and ai_digest_run_sources.user_id is null;

-- 旧系统日志没有明确所有者，保留 null 作为系统级日志。
update articles set user_id = (select id from users where username = 'admin') where user_id is null;
update ai_digest_configs set user_id = (select id from users where username = 'admin') where user_id is null;
update ai_digest_runs set user_id = (select id from users where username = 'admin') where user_id is null;

drop index if exists categories_name_unique;
drop index if exists feeds_url_unique;
drop index if exists fever_accounts_base_url_username_unique;
drop index if exists ai_digest_runs_feed_window_unique;
drop index if exists fever_feed_mappings_local_feed_id_unique;

create unique index if not exists categories_user_name_unique
  on categories (user_id, lower(name));

create unique index if not exists feeds_user_url_unique
  on feeds (user_id, url)
  where provider = 'local_rss';

create unique index if not exists fever_accounts_user_base_url_username_unique
  on fever_accounts (user_id, base_url, username);

create unique index if not exists ai_digest_runs_user_feed_window_unique
  on ai_digest_runs (user_id, feed_id, window_start_at);

create unique index if not exists fever_feed_mappings_user_local_feed_id_unique
  on fever_feed_mappings (user_id, local_feed_id);

create index if not exists categories_user_position_name_idx
  on categories (user_id, position asc, name asc);
create index if not exists feeds_user_enabled_idx
  on feeds (user_id, enabled);
create index if not exists feeds_user_category_id_idx
  on feeds (user_id, category_id);
create index if not exists articles_user_feed_published_idx
  on articles (user_id, feed_id, published_at desc, id desc);
create index if not exists articles_user_is_read_published_idx
  on articles (user_id, is_read, published_at desc, id desc);
create index if not exists articles_user_is_starred_published_idx
  on articles (user_id, is_starred, published_at desc, id desc);
create index if not exists fever_accounts_user_enabled_idx
  on fever_accounts (user_id, enabled);
create index if not exists feed_refresh_runs_user_status_idx
  on feed_refresh_runs (user_id, status);
create index if not exists system_logs_user_created_at_idx
  on system_logs (user_id, created_at desc, id desc);

alter table categories alter column user_id set not null;
alter table feeds alter column user_id set not null;
alter table articles alter column user_id set not null;
alter table fever_accounts alter column user_id set not null;
alter table fever_feed_mappings alter column user_id set not null;
alter table fever_item_mappings alter column user_id set not null;
alter table fever_sync_states alter column user_id set not null;
alter table ai_digest_configs alter column user_id set not null;
alter table ai_digest_runs alter column user_id set not null;
alter table feed_refresh_runs alter column user_id set not null;
alter table feed_refresh_run_items alter column user_id set not null;
alter table article_tasks alter column user_id set not null;
alter table article_translation_sessions alter column user_id set not null;
alter table article_translation_segments alter column user_id set not null;
alter table article_translation_events alter column user_id set not null;
alter table article_ai_summary_sessions alter column user_id set not null;
alter table article_ai_summary_events alter column user_id set not null;
alter table article_media_attachments alter column user_id set not null;
alter table feed_favicons alter column user_id set not null;
alter table ai_digest_run_sources alter column user_id set not null;
